name: Run Tests

on: [push, pull_request]

jobs:
  # API Tests (Python)
  api-tests:
    runs-on: ubuntu-latest
    env:
      ADMIN_API_KEY: "secret_api_key"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          pip install -r API/requirements.txt
          pip install pytest

      - name: Run API tests
        run: pytest API/tests/

  # CLI Tests (.NET)
  cli-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore ./VulnerabilityCLI/VulnerabilityCLI.csproj

      - name: Build CLI project
        run: dotnet build ./VulnerabilityCLI/VulnerabilityCLI.csproj --configuration Release --no-restore

      - name: Run CLI tests
        run: dotnet test ./VulnerabilityCLI.Tests/VulnerabilityCLI.Tests.csproj --configuration Release --no-build --verbosity normal